# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\Desktop\test_pyqt\proga\design\FileTestWindowDesign.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.setWindowModality(QtCore.Qt.NonModal)
        Form.resize(1075, 632)
        Form.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        Form.setWindowOpacity(1.0)
        Form.setAutoFillBackground(False)
        Form.setStyleSheet("QDialog\n"
"{\n"
"background: url(./res/file.png);\n"
"background-repeat: no-repeat;\n"
"}")
        Form.setProperty("animated", True)
        Form.setProperty("documentMode", False)
        Form.setProperty("unifiedTitleAndToolBarOnMac", False)
        self.centralwidget = QtWidgets.QWidget(Form)
        self.centralwidget.setGeometry(QtCore.QRect(0, 0, 1071, 631))
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setEnabled(True)
        self.pushButton.setGeometry(QtCore.QRect(30, 300, 271, 51))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiBold")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("QPushButton{\n"
"background-color: rgb(0, 0, 255);\n"
"color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QPushButton::hover\n"
"{\n"
"background-color : rgb(255, 0, 0);\n"
"}")
        self.pushButton.setObjectName("pushButton")
        self.downloadResultButton = QtWidgets.QPushButton(self.centralwidget)
        self.downloadResultButton.setGeometry(QtCore.QRect(500, 570, 551, 51))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiBold")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.downloadResultButton.setFont(font)
        self.downloadResultButton.setStyleSheet("QPushButton{\n"
"background-color: rgb(0, 0, 255);\n"
"color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QPushButton::hover\n"
"{\n"
"background-color : rgb(255, 0, 0);\n"
"}")
        self.downloadResultButton.setObjectName("downloadResultButton")
        self.instructionText = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.instructionText.setGeometry(QtCore.QRect(30, 120, 1021, 161))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiBold")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.instructionText.setFont(font)
        self.instructionText.setStyleSheet("QMainWindow{\n"
"background-image: url(../res/file.png);\n"
"}")
        self.instructionText.setReadOnly(True)
        self.instructionText.setObjectName("instructionText")
        self.attachFileButton = QtWidgets.QPushButton(self.centralwidget)
        self.attachFileButton.setGeometry(QtCore.QRect(330, 300, 281, 51))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiBold")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.attachFileButton.setFont(font)
        self.attachFileButton.setStyleSheet("QPushButton{\n"
"background-color: rgb(0, 0, 255);\n"
"color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QPushButton::hover\n"
"{\n"
"background-color : rgb(255, 0, 0);\n"
"}")
        self.attachFileButton.setObjectName("attachFileButton")
        self.fileNameLabel = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.fileNameLabel.setGeometry(QtCore.QRect(640, 300, 411, 51))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(18)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.fileNameLabel.setFont(font)
        self.fileNameLabel.setStyleSheet("background-color: rgb(195, 195, 195);\n"
"color: rgb(255, 255, 255);\n"
"")
        self.fileNameLabel.setLineWrapMode(QtWidgets.QPlainTextEdit.WidgetWidth)
        self.fileNameLabel.setReadOnly(True)
        self.fileNameLabel.setPlainText("")
        self.fileNameLabel.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.fileNameLabel.setBackgroundVisible(False)
        self.fileNameLabel.setObjectName("fileNameLabel")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(400, 10, 481, 61))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiBold")
        font.setPointSize(26)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.progressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar.setGeometry(QtCore.QRect(30, 370, 1021, 23))
        self.progressBar.setProperty("value", 24)
        self.progressBar.setTextVisible(True)
        self.progressBar.setInvertedAppearance(False)
        self.progressBar.setObjectName("progressBar")
        self.resultTable = QtWidgets.QTableView(self.centralwidget)
        self.resultTable.setGeometry(QtCore.QRect(30, 420, 1021, 131))
        self.resultTable.setAlternatingRowColors(False)
        self.resultTable.setObjectName("resultTable")
        self.resultTable.verticalHeader().setDefaultSectionSize(37)
        self.dropFilePic = QtWidgets.QLabel(self.centralwidget)
        self.dropFilePic.setGeometry(QtCore.QRect(0, 0, 1071, 631))
        self.dropFilePic.setStyleSheet("QDialog{\n"
"background-image: url(../res/file.png);\n"
"}")
        self.dropFilePic.setText("")
        self.dropFilePic.setPixmap(QtGui.QPixmap("D:\\Desktop\\test_pyqt\\proga\\design\\../res/drop-file.png"))
        self.dropFilePic.setObjectName("dropFilePic")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Тестирование по файлу"))
        self.pushButton.setText(_translate("Form", "ОТПРАВИТЬ"))
        self.downloadResultButton.setText(_translate("Form", "СКАЧАТЬ ФАЙЛ С РЕЗУЛЬТАТАМИ"))
        self.instructionText.setPlainText(_translate("Form", "Text  Text  Text  Text  Text  Text  Text  Text  Text  Text  Text  Text  Text  Text  Text  Text  Text  Text  Text  Text  Text  Text  Text  Text  Text  Text  Text  Text  Text  Text  Text  Text  Text  Text  Text  Text  Text  Text  Text  Text  Text  Text  Text  Text  Text  Text  Text  Text  Text  Text  Text  Text  Text  Text  Text  Text  Text  Text  Text  Text  Text  Text  Text  Text  Text  Text  Text  Text  Text  Text  Text  Text  Text  Text  Text  Text  Text  Text  Text  Text  Text  Text  Text  Text  Text  Text  Text  Text  Text  Text  Text  Text  Text  Text  Text  Text  Text  Text  Text  Text  Text  Text  Text  Text  Text  Text  Text  Text  Text  Text  Text  Text  Text  Text  Text  Text  Text  Text  Text  Text  Text  Text  Text  Text  Text  Text  Text  Text  Text  Text  Text  Text  Text  Text  Text  Text  Text  Text  Text  Text  Text  Text  Text  "))
        self.attachFileButton.setText(_translate("Form", "ПРИКРЕПИТЬ"))
        self.label.setText(_translate("Form", "Тестирование по файлу"))
        self.progressBar.setFormat(_translate("Form", "%p% обработано"))
