# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\Desktop\test_pyqt\proga\design\StartHelpWindowDesign.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1073, 636)
        Form.setAutoFillBackground(False)
        Form.setStyleSheet("QMainWindow\n"
"{\n"
"background: url(./res/start.png);\n"
"background-repeat: no-repeat;\n"
"}")
        self.centralwidget = QtWidgets.QWidget(Form)
        self.centralwidget.setObjectName("centralwidget")
        self.nextButton = QtWidgets.QPushButton(self.centralwidget)
        self.nextButton.setGeometry(QtCore.QRect(40, 570, 181, 51))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiBold")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.nextButton.setFont(font)
        self.nextButton.setStyleSheet("QPushButton{\n"
"background-color: rgb(0, 0, 255);\n"
"color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QPushButton::hover\n"
"{\n"
"background-color : rgb(255, 0, 0);\n"
"}")
        self.nextButton.setObjectName("nextButton")
        self.helpText = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.helpText.setGeometry(QtCore.QRect(40, 140, 451, 411))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(11)
        self.helpText.setFont(font)
        self.helpText.setReadOnly(True)
        self.helpText.setObjectName("helpText")
        Form.setCentralWidget(self.centralwidget)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Приветствие"))
        self.nextButton.setText(_translate("Form", "ДАЛЕЕ"))
        self.helpText.setPlainText(_translate("Form", "Приветствуем Вас в демо-версии программы анализа эмоционального окраса текстовых сообщений.\n"
"В данной версии у Вас есть возможность проанализировать сообщение, введенное самостоятельно, или же загрузить файл* с набором сообщений для анализа.\n"
"После анализа сообщение будет получениа слудующая информация:\n"
"• Рекомендации для оператора, как стоит поступить после получения последнего сообщения;\n"
"• Процентное соотношение каждого из эмоциональных окрасов сообщения (позитивное, нейтральное, негативное).\n"
"\n"
"*файл должен представлять формат, подобный тому, что был предоставлен для тестов"))
