# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\Desktop\test_pyqt\proga\design\TextTestWindowDesign.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.setWindowModality(QtCore.Qt.NonModal)
        Form.resize(1101, 656)
        Form.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        Form.setWindowOpacity(1.0)
        Form.setAutoFillBackground(False)
        Form.setStyleSheet("QMainWindow\n"
"{\n"
"background: url(./res/text.png);\n"
"background-repeat: no-repeat;\n"
"}")
        Form.setToolButtonStyle(QtCore.Qt.ToolButtonTextOnly)
        Form.setAnimated(True)
        Form.setDocumentMode(False)
        Form.setTabShape(QtWidgets.QTabWidget.Triangular)
        Form.setUnifiedTitleAndToolBarOnMac(False)
        self.centralwidget = QtWidgets.QWidget(Form)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(70, 340, 581, 51))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiBold")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("QPushButton{\n"
"background-color: rgb(0, 0, 255);\n"
"color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QPushButton::hover\n"
"{\n"
"background-color : rgb(255, 0, 0);\n"
"}")
        self.pushButton.setObjectName("pushButton")
        self.uploadFileButton = QtWidgets.QPushButton(self.centralwidget)
        self.uploadFileButton.setGeometry(QtCore.QRect(70, 540, 461, 51))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiBold")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.uploadFileButton.setFont(font)
        self.uploadFileButton.setStyleSheet("QPushButton{\n"
"background-color: rgb(0, 0, 255);\n"
"color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QPushButton::hover\n"
"{\n"
"background-color : rgb(255, 0, 0);\n"
"}")
        self.uploadFileButton.setObjectName("uploadFileButton")
        self.plainTextEdit = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.plainTextEdit.setGeometry(QtCore.QRect(70, 160, 731, 161))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiBold")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.plainTextEdit.setFont(font)
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.plainTextEdit_2 = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.plainTextEdit_2.setGeometry(QtCore.QRect(70, 410, 581, 111))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiBold")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.plainTextEdit_2.setFont(font)
        self.plainTextEdit_2.setReadOnly(True)
        self.plainTextEdit_2.setObjectName("plainTextEdit_2")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(70, 110, 291, 31))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiBold")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        Form.setCentralWidget(self.centralwidget)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Тестирование по комментарию"))
        self.pushButton.setText(_translate("Form", "ОТПРАВИТЬ"))
        self.uploadFileButton.setText(_translate("Form", "ЗАГРУЗИТЬ ФАЙЛ"))
        self.label.setText(_translate("Form", "Введите комментарий:"))
